### ISSUE TITLE
`helicsInputGetComplex` errored with message `invalid data size` in Julia and Python

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#1493] opened 2020-07-22 03:54 UTC
**Describe the bug**

![Screen Shot 2020-07-21 at 9 52 04 PM](https://user-images.githubusercontent.com/1813121/88132329-6e0e7780-cb9c-11ea-99f8-fc964f43e038.png)

**Environment (please complete the following information):**

- Operating System: [Mac]
- Language Extension: [Python | Julia]
- `conda install -c gmlc-tdc helics && julia -e "using Pkg; Pkg.add("HELICS")` 
- HELICS version: 2.5.2 (2020-06-14)

Zip files contain only the julia MWE.

[Archive.zip](https://github.com/GMLC-TDC/HELICS/files/4957701/Archive.zip)

Python examples are not working because of this issue:

https://github.com/GMLC-TDC/HELICS/issues/1492

I don't see anything wrong with the json files:

```json
{
    "name": "fed_1",
    "loglevel": 7,
    "coreType": "zmq",
    "period": 0.25,
    "uninterruptible": false,
    "wait_for_current_time_update": false,
    "publications": [
        {
            "global": true,
            "key": "value_1",
            "type": "complex"
        }
    ],
    "subscriptions": [
        {
            "required": true,
            "key": "value_2",
            "type": "complex"
        }
    ]
}
```

```json
{
    "name": "fed_2",
    "loglevel": 7,
    "coreType": "zmq",
    "period": 0.5,
    "uninterruptible": false,
    "wait_for_current_time_update": true,
    "publications": [
        {
            "global": true,
            "key": "value_2",
            "type": "complex"
        }
    ],
    "subscriptions": [
        {
            "required": true,
            "key": "value_1",
            "type": "complex"
        }
    ]
}
```

**Comment by phlptp** [comment] 2020-08-06 00:03
@kdheepak   is there another federate in the co-simulation that provides value_1?  

what would the expected result be if a helicsInputGetComplex is called but no input has been received and no default was given?

**Comment by phlptp** [comment] 2020-08-06 13:37
@kdheepak  can you try this with the complex_test branch?  I doubt that fixes it, but I did make the error message a little more informative (hopefully).

As best as I can tell this error would occur if there is a mismatch between the expected data type and what was actually sent.  I haven't successfully replicated how you are doing this yet so not sure where the problem is yet.  

It will also be fixed in helics3 since the data serialization will change to have more information so this problem wouldn't occur.

**Comment by kdheepak** [comment] 2020-08-11 17:47
In this example, there is a default set? So why does it still error?

**Closed** 2020-08-24 23:28 UTC
Labels: bug
