### ISSUE TITLE
helics::HelicsException: TEST core is not available

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#918] opened 2019-11-23 12:53 UTC
I'm getting a segfault when running Julia with HELICS v2.3.1.

```julia
$ julia --startup-file=no --project 
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.3.0-rc4.1 (2019-10-15)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using HELICS

julia> const h = HELICS
HELICS

julia> h.helicsGetVersion()
"2.3.1 (2019-11-22)"

julia> h.helicsCreateCore("test", "core1", "--autobroker")
libc++abi.dylib: terminating with uncaught exception of type helics::HelicsException: TEST core is not available

signal (6): Abort trap: 6
in expression starting at REPL[4]:1
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 1757642 (Pool: 1757254; Big: 388); GC: 2
[1]    37599 abort      /Users/USER/Applications/Julia-1.3.app/Contents/Resources/julia/bin/julia
```

**Comment by kdheepak** [comment] 2019-11-23 13:02
<img width="1551" alt="Screen Shot 2019-11-23 at 5 54 30 AM" src="https://user-images.githubusercontent.com/1813121/69479018-035f2f00-0db6-11ea-95f1-6d65395c8258.png">

[This change](https://github.com/GMLC-TDC/HELICS/commit/02c450f37b3dbe140ecd7611da67cc78eebc976b#diff-af3b638bc2a3e6c650974192a53c7291R391) is what is causing the issue. I have tests in HELICS.jl that use the `test` core but I'm building the shared library with `-DHELICS_BUILD_TESTS=OFF`. I'll update the Julia tests to not use the `test` core since we don't expect users to be using that.

**Comment by kdheepak** [comment] 2019-11-23 13:03
I'm reopening this since this causes a segfault. This should have thrown an error in Julia instead.

**Comment by phlptp** [comment] 2019-11-23 13:54
It looks like HELICS is throwing an exception as expected.    You could run with the "inproc" core instead or add the 'ENABLE_TEST_CORE=ON' flag to the build.     Essentially what happened was the cores diverged enough that it made sense to split them.  There is no reason for a user to use the "test" core unless they are doing some testing, and the "inproc" core is a duplicate of the functionality of the previous test core just with a more sensical name.

**Comment by phlptp** [comment] 2019-11-23 14:08
On second look you are correct one of those function did not have the error traps around the important parts to catch that kind of exception in the C shared library.

**Closed** 2019-11-24 22:59 UTC
Labels: bug
