### ISSUE TITLE
Add support to clang format workflow for PRs from forks

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/HELICS#1022] opened 2020-01-14 17:34 UTC
**Describe the bug**
The clang-format source code formatting workflow fails to checkout the head ref when running on a PR from a fork.

**What is the expected behavior?**
It should checkout the code correctly and either report if formatting will be needed, or open a formatting PR (may not be possible due to permissions).

**Comment by phlptp** [comment] 2020-01-14 17:38
This is a duplicate of #971

**Closed** 2020-01-14 17:42 UTC
Labels: bug, duplicate
