### ISSUE TITLE
Python3 str objects not accepted by HELICS python interface

### ISSUE THREAD

**Issue by yee29** [GMLC-TDC/HELICS#1325] opened 2020-05-14 14:53 UTC
**Describe the bug**
There seems to be a difference in how Python3 and Python2 handles strings when using SWIG to convert C to Python. This is caused when building the python interface from HELICS and using Python3 strings when calling functions. Since I think the HELICS interface was written for Python2, it assumes all strings are byte strings and in Python3 strings are character strings. Related: https://stackoverflow.com/questions/48391926/python-swig-in-typemap-does-not-work

**What is the expected behavior?**
Should not have to convert strings in Python3 to byte strings in order to call functions that need strings as arguments. 

**To Reproduce**
```
    fedArgs.extend([b"--loglevel=5", b"--period=1.0"])
    a=["--federates=2", "--loglevel=5", "--period=1.0"]
    fedinfo = h.helicsCreateFederateInfo()
    h.helicsFederateInfoLoadFromArgs(fedinfo, fedArgs)
```
If I call helicsFederateInfoLoadFromArgs(fedinfo, a) I will get TypeError: list must contain strings from Python. The current work around is to convert the strings in the list to byte strings like I have show in fedArgs.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Language Extension: Python
 - Compiler: GCC 9.2.0/SPACK
 - HELICS version: 2.5.0

**Additional context and information**
 https://stackoverflow.com/questions/48391926/python-swig-in-typemap-does-not-work

**Comment by phlptp** [comment] 2020-05-14 15:05
I am guessing this is particular to the *FromArgs functions since those use a particular swig template that we haven't spent much time on for python.  Those ideally take an array of strings for the Args operations to translate to the underlying int argc, char *argv[] arguments in C.

**Comment by kdheepak** [comment] 2020-05-14 18:58
In Python, if I have the following program:

```python
import sys

print(type(sys.argv[0]))
print(type(sys.argv[1]))
```

This is what I get:

```
$ python test.py hello
<class 'str'>
<class 'str'>
```

It is always a string, and not a byte array. So we should make the API also allow only a list of unicode strings instead of a list of byte strings.

**Comment by kdheepak** [comment] 2020-05-16 21:38
I think all these functions are not doing the right thing:

```python
$ rg helicsCreateBrokerFromArgs
helics.py
492:def helicsCreateBrokerFromArgs(type: "char const *", name: "char const *", argc: "int") -> "helics_broker":
508:return _helics.helicsCreateBrokerFromArgs(type, name, argc)

$ rg helicsCreateCoreFromArgs
helics.py
431:def helicsCreateCoreFromArgs(type: "char const *", name: "char const *", argc: "int") -> "helics_core":
447:return _helics.helicsCreateCoreFromArgs(type, name, argc)

$ rg helicsFederateInfoLoadFromArgs
helics.py
950:def helicsFederateInfoLoadFromArgs(fi: "helics_federate_info", argc: "int") -> "void":
961:return _helics.helicsFederateInfoLoadFromArgs(fi, argc)
```

These are the signatures for these three functions:

```c
src/helics/shared_api_library/helics.h
99:helicsCreateCoreFromArgs(const char* type, const char* name, int argc, const char* const* argv, helics_error* err);
157:helicsCreateBrokerFromArgs(const char* type, const char* name, int argc, const char* const* argv, helics_error* err);
578:helicsFederateInfoLoadFromArgs(helics_federate_info fi, int argc, const char* const* argv, helics_error*);
```

And this is the typemap:

```

//typemap for the input arguments
%typemap(in) (int argc, const char *const *argv) {
  /* Check if is a list */
  if (PyList_Check($input)) {
    int i;
    $1 = (int)(PyList_Size($input));
    $2 = (char **) malloc(($1+1)*sizeof(char *));
    for (i = 0; i < $1; i++) {
      PyObject *o = PyList_GetItem($input,i);
      if (PyString_Check(o))
    $2[i] = PyString_AsString(PyList_GetItem($input,i));
      else {
    PyErr_SetString(PyExc_TypeError,"list must contain strings");
    free($2);
    return NULL;
      }
    }
    $2[i] = 0;
  } else {
    PyErr_SetString(PyExc_TypeError,"not a list");
    return NULL;
  }
}
```

I think the issue is that this typemap works, but is using `int argc` for the Python argument.

Every other function that accepts a list and the size of the list has the input arguments in the reverse order, so this is why it is not a problem for remaining functions.

**Comment by phlptp** [comment] 2020-05-26 15:18
If we are going to make a change here we should do it this week.

**Comment by kdheepak** [comment] 2020-05-26 20:26
I'll look into it in more detail this week.

**Comment by kdheepak** [comment] 2020-08-26 19:50
This is fixed in the new Python `pyhelics` interface.

**Closed** 2020-10-07 00:00 UTC
Labels: bug
