### ISSUE TITLE
CMAKE error while installing master in Linux

### ISSUE THREAD

**Issue by priyatm62** [GMLC-TDC/HELICS#1445] opened 2020-06-25 19:01 UTC
- **I'm submitting a ...**
  - [ x] bug

### Bug

1. **What is the current behavior?**
While installing, cmake and make are successful. During make install, the following error comes (username replaced) -
CMAKE error: File install cannot find 
"/home/<user>/HelicsInstall/lib/libhelics-shared.so.2.5.2".

When I browse to the installation location, there is a file with the following name in Camel case and not dashes,
/home/<user>/HelicsInstall/lib/libhelicsSharedLib.so.2.5.2

1. **What is the expected behavior? What is the motivation / use case for changing the behavior?**

1. **What are the steps to reproduce this bug? Please provide a minimal working example of the bug if possible.**
 mkdir ${HELICS_INSTALL}
 cd ${HELICS_INSTALL}
 cmake {HELICS_SOURCE} -DCMAKE_INSTALL_PREFIX=${HELICS_INSTALL} -DBUILD_PYTHON_INTERFACE=ON -DCMAKE_BUILD_TYPE=Release -DHELICS_BUILD_CXX_SHARED_LIB=ON -DHELICS_BUILD_TESTS=OFF -DHELICS_BUILD_EXAMPLES=OFF
make -j 4
make install

1. **Please tell us about your environment:**
Helics master cloned on 06/24

- Operating System: [ Linux]
- Language Extension: [ Python ]

- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by priyatm62** [comment] 2020-06-25 19:17
Same error in develop as well

**Comment by kdheepak** [comment] 2020-06-25 19:24
Can you try it without this flag `-DHELICS_BUILD_CXX_SHARED_LIB=ON`?

**Comment by priyatm62** [comment] 2020-06-26 00:38
I am getting this error during make install - 
CMake Error at src/helics/apps/cmake_install.cmake:47
file INSTALL cannot find "/home/<username>/HelicsInstall/bin/helics_player"

And that binary is not there in bin. There is helics-config, helics_app, helics_broker, helics_broker_server and helics_recorder.

I am using the latest develop branch

**Comment by phlptp** [comment] 2020-06-30 23:38
what platform are you using.  Specific linux variant, compiler, etc?  We do have some tests that pass that do this so I think it is something platform specific, but I am confused as to what might be going on.

**Comment by nightlark** [comment] 2020-07-01 05:46
Someone else at LLNL had a similar error recently, using gcc 4.9 on I think a Debian derived distro. The solution was setting `CMAKE_CXX_FLAGS` with the C99 flags from this section of the install docs: https://docs.helics.org/en/latest/installation/linux.html#notes-for-ubuntu

**Comment by phlptp** [comment] 2020-07-07 19:00
It looks like this is bug in the circumstance where the CMAKE_INSTALL_PREFIX is set to the same location as the build directory.

**Comment by nightlark** [comment] 2020-07-07 19:07
Yea. I'm adding a check for it. I guess before it worked in some cases because the binaries and libraries were scattered throughout the build tree instead of in folders that match an install prefix.

**Comment by phlptp** [comment] 2020-07-07 19:08
Do we know the actual cause of the issue so it could work in that case?

**Comment by nightlark** [comment] 2020-07-07 19:18
The cause of the issue is setting the output locations for things in the build tree that happened here: https://github.com/GMLC-TDC/HELICS/commit/356bdb40891e9452e1398f209eee324b0ea877c5#diff-af3b638bc2a3e6c650974192a53c7291R113-R120

**Comment by nightlark** [comment] 2020-07-07 19:21
The only way to make it work again would be reverting that change. Though in general I don't think the install prefix should be getting set to the build folder.

**Comment by phlptp** [comment] 2020-07-07 19:48
Right,  there isn't much purpose to that now that things are automatically built in a common binary location.  So A clear error message is probably sufficient.

**Comment by priyatm62** [comment] 2020-07-08 16:37
@phlptp 
Platform info - Ubuntu 18.04.2
Compilers available- g++, g++7, gcc, gcc-7, gcc-9. Not sure which is being used.
I was trying to build helics in a different folder, outside of the source.

**Comment by priyatm62** [comment] 2020-07-08 17:05
I used the flags mentioned in https://docs.helics.org/en/latest/installation/linux.html#notes-for-ubuntu . My cmake command below while installing master. 
cmake ../HELICS-src-06-2020/HELICS -DCMAKE_INSTALL_PREFIX=/home/thek306/HelicsInstall/ -DBUILD_PYTHON_INTERFACE=ON -DCMAKE_BUILD_TYPE=Release -DHELICS_BUILD_TESTS=OFF -DHELICS_BUILD_EXAMPLES=OFF -DCMake_CXX_FLAGS="-D_GLIBCXX_USE_C99 -D_GLIBCXX_USE_C99_MATH"

And the error I get during make install -
CMake Error at src/helics/apps/cmake_install.cmake:47 (file):
file INSTALL cannot find "/home/thek306/HelicsInstall/bin/helics_player".

**Comment by nightlark** [comment] 2020-07-08 17:08
Can you try that again with -DCMAKE_CXX_FLAGS="-D_GLIBCXX_USE_C99 -D_GLIBCXX_USE_C99_MATH" instead of -DCMake_CXX_FLAGS="-D_GLIBCXX_USE_C99 -D_GLIBCXX_USE_C99_MATH" ?

**Comment by priyatm62** [comment] 2020-07-08 19:28
same error during make install with the suggested cmake below -
mkdir HelicsInstall
cd HelicsInstall
cmake ../HELICS-src-06-2020/HELICS -DCMAKE_INSTALL_PREFIX=/home/thek306/HelicsInstall/ -DBUILD_PYTHON_INTERFACE=ON -DCMAKE_BUILD_TYPE=Release -DHELICS_BUILD_TESTS=OFF -DHELICS_BUILD_EXAMPLES=OFF -DCMAKE_CXX_FLAGS="-D_GLIBCXX_USE_C99 -D_GLIBCXX_USE_C99_MATH"

~/HelicsInstall/bin/ has the following files, and missing helics_player -
helics-config
helics_app
helics_broker
helics_broker_server
helics_recorder

**Comment by phlptp** [comment] 2020-08-03 12:52
@nightlark did we get this resolved and is there anything we need to do in the build configuration that would help?

**Comment by nightlark** [comment] 2020-08-03 22:04
We made a change that stops the configuration early if the install folder is inside the build folder. I'm unable to reproduce the error in this other scenario on my Ubuntu 18.04 VM. @priyatm62 I think this will require finding a time to screen share so that we can see what's going on with the machine you're building on.

**Comment by nightlark** [comment] 2020-08-03 23:19
@phlptp actually, I just took a closer look at the commands Priya used -- it's the exact same problem just using a build folder with a different name, so the change in develop already addresses the issue; in the next release of HELICS running CMake configure will give a fatal error if the build folder used for running CMake and the folder to install to are the same.

@priyatm62 here's the parts of the commands that are causing the error:
```
mkdir HelicsInstall
cd HelicsInstall
cmake ../HELICS-src-06-2020/HELICS -DCMAKE_INSTALL_PREFIX=/home/thek306/HelicsInstall/
<rest of the cmake options>
```
CMake is getting run to configure the project build inside the `HelicsInstall` folder, and I'm guessing `mkdir` and `cd` are getting run from inside your home folder -- this means the `HelicsInstall` is the build folder that's created has an real absolute path name of `/home/thek306/HelicsInstall/`. Setting `CMAKE_INSTALL_PREFIX` to `/home/thek306/HelicsInstall` is setting the install folder to the same folder as is being used for the build, which results in conflicts between temporary compiled files in the build folder and installed files with the same names.

The build folder (the one CMake is run from) should be completely different from the folder CMAKE_INSTALL_PREFIX is set to.

Something like this will work (or any other names, as long as the `mkdir` and `cd` commands use a folder that is not the same as the folder CMAKE_INSTALL_PREFIX is set to):
```
mkdir HelicsCmakeBuildFolder
cd HelicsCmakeBuildFolder
cmake ../HELICS-src-06-2020/HELICS -DCMAKE_INSTALL_PREFIX=/home/thek306/HelicsInstallFolder/
<rest of the cmake options>
```

**Comment by phlptp** [comment] 2020-08-07 12:26
I am going to close this issue, since the root cause is known and is now checked.

**Closed by phlptp** 2020-08-07 12:26 UTC
Labels: bug
