### ISSUE TITLE
Issue loading `helics` in Python on Windows

### ISSUE THREAD

**Issue by kdheepak** [GMLC-TDC/HELICS#1139] opened 2020-03-13 17:45 UTC
Users are getting the same issue using `pip` and `conda` with Python 3.7.

<img width="659" alt="Screen Shot 2020-03-13 at 11 41 37 AM" src="https://user-images.githubusercontent.com/1813121/76645978-b6979380-651f-11ea-88ee-e074e13924a1.png">

This does not seem to be an issue with the Windows binary installation.

**Comment by nightlark** [comment] 2020-03-13 17:57
I'm not seeing this issue with pip install on Linux.

**Comment by kdheepak** [comment] 2020-03-13 17:58
It appears to be Windows only. The issue does not exist on `2.3.1`.

**Comment by nightlark** [comment] 2020-03-13 18:03
What do you mean by Windows binary installation?

**Comment by kdheepak** [comment] 2020-03-13 18:16
I meant the Windows exe installer that we have on the releases page.

**Comment by kdheepak** [comment] 2020-03-13 18:21
When a user runs `pip install helics`, does it not install zeromq? How do you check what the dependencies are for a helics shared library from the command line?

**Comment by nightlark** [comment] 2020-03-13 18:26
The Windows shared libraries static link zeromq.

**Comment by kdheepak** [comment] 2020-03-13 18:27
It's failing when it tried to load `_helics.pyd`. I checked in the folder and it exists.

**Comment by nightlark** [comment] 2020-03-13 18:28
Does the helics shared lib dll also exist in the folder?

**Comment by nightlark** [comment] 2020-03-13 19:04
Hm. I'm not able to reproduce the error on my Python 3.7.7 (64-bit) install on Windows.

**Comment by kdheepak** [comment] 2020-03-13 19:05
Is it a Anaconda Python install?

**Comment by nightlark** [comment] 2020-03-13 19:06
It's a python.org install using a virtualenv.

**Comment by nightlark** [comment] 2020-03-13 19:12
I tried using a Python 3.7 conda environment, it worked with pip.

**Comment by nightlark** [comment] 2020-03-13 19:25
The only dependency that comes to mind would be if they don't have the right VC Runtime installed (vcruntime140 - https://www.microsoft.com/en-ca/download/details.aspx?id=48145). As far as I can tell, vcruntime140 is the closest thing to a "standard" runtime library version dependency for native Windows Python extensions.

**Comment by nightlark** [comment] 2020-03-13 19:29
Can a webex/skype get set up with the person having issues? This sounds like it might be specific to their setup (or some organization Windows base install image).

**Comment by nightlark** [comment] 2020-03-18 22:15
@kdheepak any updates on this? I haven't been able to reproduce the error on my Windows computers.

**Comment by kdheepak** [comment] 2020-03-19 16:11
People are still experiencing this. 

![thumbnail_screenshot](https://user-images.githubusercontent.com/1813121/77088302-e0423600-69c9-11ea-8bea-53441517902b.png)

I'll try to reproduce or get access to a machine where this happens and set up a call with you.

**Comment by kdheepak** [comment] 2020-03-19 16:22
Unfortunately, on the only Windows instance I have access to I'm not able to reproduce this issue.

<img width="848" alt="Screen Shot 2020-03-19 at 10 21 14 AM" src="https://user-images.githubusercontent.com/1813121/77089416-68750b00-69cb-11ea-83f9-0171f0cc5bb1.png">

**Comment by jhuang54** [comment] 2020-03-19 16:45
I have this problem. Can I do something for you?

**Comment by nightlark** [comment] 2020-03-19 17:47
@jhuang54 yes! There are two things that would help narrow down the problem -- first would be if you could upload a zip file with the two helics related subfolders in `C:\Anaconda3\envs\helics-env\lib\site-packages\` then I can try it out on my system and see if it's a missing system dependency or the package. The other would be if we can schedule a webex/skype/zoom/ghangouts screen sharing session to debug the problem and come up with a fix.

**Comment by jhuang54** [comment] 2020-03-19 18:12
[helics2.3.1_site-packages.zip](https://github.com/GMLC-TDC/HELICS/files/4356248/helics2.3.1_site-packages.zip)
[helics_site-packages.zip](https://github.com/GMLC-TDC/HELICS/files/4356254/helics_site-packages.zip)

where helics_2.3.1 is helics 2.3.1

**Comment by kdheepak** [comment] 2020-03-23 16:36
Installing https://aka.ms/vs/16/release/vc_redist.x64.exe resolves this issue.

**Comment by kdheepak** [comment] 2020-03-23 16:43
The specific issue here (at least on one machine that we looked at) was that `VCRUNTIME140_1.dll` was missing on the host machine. This might come with Anaconda, but I think it's safe to say that users should always install the latest Visual C++ Redistributable. You can find links to the downloads here:

https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by kdheepak** [comment] 2020-03-23 16:47
We used this tool to identify what the missing dependencies were for the `helicsSharedLib.dll`:

https://github.com/lucasg/Dependencies

**Comment by nightlark** [comment] 2020-03-23 16:50
On a working install, the dependencies found will look similar to the screenshot (only not finding WS2_32.dll). A missing vcruntime140_1.dll will be fixed by following the steps in https://github.com/GMLC-TDC/HELICS/issues/1139#issuecomment-602719129 above.

![Capture](https://user-images.githubusercontent.com/3969255/77341136-830cf400-6ceb-11ea-8e46-ccea0ca74abe.PNG)

**Closed** 2020-04-24 21:20 UTC
Labels: bug
